In [1]:
import pandas as pd
import numpy as np
import os
import sys
import country_dicts

In [2]:
print(sys.path)

['/home/chidurah/Projects/Surveillance/Surveillance Processing', '/opt/anaconda3/lib/python38.zip', '/opt/anaconda3/lib/python3.8', '/opt/anaconda3/lib/python3.8/lib-dynload', '', '/home/chidurah/.local/lib/python3.8/site-packages', '/opt/anaconda3/lib/python3.8/site-packages', '/opt/anaconda3/lib/python3.8/site-packages/locket-0.2.1-py3.8.egg', '/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/home/chidurah/.ipython']

In [3]:
country_dicts

In [4]:
from country_dicts import name_to_alpha_2

In [5]:
name_to_alpha_2

{'Aruba': 'AW',
 'Afghanistan': 'AF',
 'Angola': 'AO',
 'Anguilla': 'AI',
 'Åland Islands': 'AX',
 'Albania': 'AL',
 'Andorra': 'AD',
 'United Arab Emirates': 'AE',
 'Argentina': 'AR',
 'Armenia': 'AM',
 'American Samoa': 'AS',
 'Antarctica': 'AQ',
 'French Southern Territories': 'TF',
 'Antigua and Barbuda': 'AG',
 'Australia': 'AU',
 'Austria': 'AT',
 'Azerbaijan': 'AZ',
 'Burundi': 'BI',
 'Belgium': 'BE',
 'Benin': 'BJ',
 'Bonaire, Sint Eustatius and Saba': 'BQ',
 'Burkina Faso': 'BF',
 'Bangladesh': 'BD',
 'Bulgaria': 'BG',
 'Bahrain': 'BH',
 'Bahamas': 'BS',
 'Bosnia and Herzegovina': 'BA',
 'Saint Barthélemy': 'BL',
 'Belarus': 'BY',
 'Belize': 'BZ',
 'Bermuda': 'BM',
 'Bolivia, Plurinational State of': 'BO',
 'Brazil': 'BR',
 'Barbados': 'BB',
 'Brunei Darussalam': 'BN',
 'Bhutan': 'BT',
 'Bouvet Island': 'BV',
 'Botswana': 'BW',
 'Central African Republic': 'CF',
 'Canada': 'CA',
 'Cocos (Keeling) Islands': 'CC',
 'Switzerland': 'CH',
 'Chile': 'CL',
 'China': 'CN',
 "Côte d'Ivoire": 'CI',
 'Cameroon': 'CM',
 'Congo, The Democratic Republic of the': 'CD',
 'Congo': 'CG',
 'Cook Islands': 'CK',
 'Colombia': 'CO',
 'Comoros': 'KM',
 'Cabo Verde': 'CV',
 'Costa Rica': 'CR',
 'Cuba': 'CU',
 'Curaçao': 'CW',
 'Christmas Island': 'CX',
 'Cayman Islands': 'KY',
 'Cyprus': 'CY',
 'Czechia': 'CZ',
 'Germany': 'DE',
 'Djibouti': 'DJ',
 'Dominica': 'DM',
 'Denmark': 'DK',
 'Dominican Republic': 'DO',
 'Algeria': 'DZ',
 'Ecuador': 'EC',
 'Egypt': 'EG',
 'Eritrea': 'ER',
 'Western Sahara': 'EH',
 'Spain': 'ES',
 'Estonia': 'EE',
 'Ethiopia': 'ET',
 'Finland': 'FI',
 'Fiji': 'FJ',
 'Falkland Islands (Malvinas)': 'FK',
 'France': 'FR',
 'Faroe Islands': 'FO',
 'Micronesia, Federated States of': 'FM',
 'Gabon': 'GA',
 'United Kingdom': 'GB',
 'Georgia': 'GE',
 'Guernsey': 'GG',
 'Ghana': 'GH',
 'Gibraltar': 'GI',
 'Guinea': 'GN',
 'Guadeloupe': 'GP',
 'Gambia': 'GM',
 'Guinea-Bissau': 'GW',
 'Equatorial Guinea': 'GQ',
 'Greece': 'GR',
 'Grenada': 'GD',
 'Greenland': 'GL',
 'Guatemala': 'GT',
 'French Guiana': 'GF',
 'Guam': 'GU',
 'Guyana': 'GY',
 'Hong Kong': 'HK',
 'Heard Island and McDonald Islands': 'HM',
 'Honduras': 'HN',
 'Croatia': 'HR',
 'Haiti': 'HT',
 'Hungary': 'HU',
 'Indonesia': 'ID',
 'Isle of Man': 'IM',
 'India': 'IN',
 'British Indian Ocean Territory': 'IO',
 'Ireland': 'IE',
 'Iran, Islamic Republic of': 'IR',
 'Iraq': 'IQ',
 'Iceland': 'IS',
 'Israel': 'IL',
 'Italy': 'IT',
 'Jamaica': 'JM',
 'Jersey': 'JE',
 'Jordan': 'JO',
 'Japan': 'JP',
 'Kazakhstan': 'KZ',
 'Kenya': 'KE',
 'Kyrgyzstan': 'KG',
 'Cambodia': 'KH',
 'Kiribati': 'KI',
 'Saint Kitts and Nevis': 'KN',
 'Korea, Republic of': 'KR',
 'Kuwait': 'KW',
 "Lao People's Democratic Republic": 'LA',
 'Lebanon': 'LB',
 'Liberia': 'LR',
 'Libya': 'LY',
 'Saint Lucia': 'LC',
 'Liechtenstein': 'LI',
 'Sri Lanka': 'LK',
 'Lesotho': 'LS',
 'Lithuania': 'LT',
 'Luxembourg': 'LU',
 'Latvia': 'LV',
 'Macao': 'MO',
 'Saint Martin (French part)': 'MF',
 'Morocco': 'MA',
 'Monaco': 'MC',
 'Moldova, Republic of': 'MD',
 'Madagascar': 'MG',
 'Maldives': 'MV',
 'Mexico': 'MX',
 'Marshall Islands': 'MH',
 'North Macedonia': 'MK',
 'Mali': 'ML',
 'Malta': 'MT',
 'Myanmar': 'MM',
 'Montenegro': 'ME',
 'Mongolia': 'MN',
 'Northern Mariana Islands': 'MP',
 'Mozambique': 'MZ',
 'Mauritania': 'MR',
 'Montserrat': 'MS',
 'Martinique': 'MQ',
 'Mauritius': 'MU',
 'Malawi': 'MW',
 'Malaysia': 'MY',
 'Mayotte': 'YT',
 'Namibia': 'NA',
 'New Caledonia': 'NC',
 'Niger': 'NE',
 'Norfolk Island': 'NF',
 'Nigeria': 'NG',
 'Nicaragua': 'NI',
 'Niue': 'NU',
 'Netherlands': 'NL',
 'Norway': 'NO',
 'Nepal': 'NP',
 'Nauru': 'NR',
 'New Zealand': 'NZ',
 'Oman': 'OM',
 'Pakistan': 'PK',
 'Panama': 'PA',
 'Pitcairn': 'PN',
 'Peru': 'PE',
 'Philippines': 'PH',
 'Palau': 'PW',
 'Papua New Guinea': 'PG',
 'Poland': 'PL',
 'Puerto Rico': 'PR',
 "Korea, Democratic People's Republic of": 'KP',
 'Portugal': 'PT',
 'Paraguay': 'PY',
 'Palestine, State of': 'PS',
 'French Polynesia': 'PF',
 'Qatar': 'QA',
 'Réunion': 'RE',
 'Romania': 'RO',
 'Russian Federation': 'RU',
 'Rwanda': 'RW',
 'Saudi Arabia': 'SA',
 'Sudan': 'SD',
 'Senegal': 'SN',
 'Singapore': 'SG',
 'South Georgia and the South Sandwich Islands': 'GS',
 'Saint Helena, Ascension and Tristan da Cunha': 'SH',
 'Svalbard and Jan Mayen': 'SJ',
 'Solomon Islands': 'SB',
 'Sierra Leone': 'SL',
 'El Salvador': 'SV',
 'San Marino': 'SM',
 'Somalia': 'SO',
 'Saint Pierre and Miquelon': 'PM',
 'Serbia': 'RS',
 'South Sudan': 'SS',
 'Sao Tome and Principe': 'ST',
 'Suriname': 'SR',
 'Slovakia': 'SK',
 'Slovenia': 'SI',
 'Sweden': 'SE',
 'Eswatini': 'SZ',
 'Sint Maarten (Dutch part)': 'SX',
 'Seychelles': 'SC',
 'Syrian Arab Republic': 'SY',
 'Turks and Caicos Islands': 'TC',
 'Chad': 'TD',
 'Togo': 'TG',
 'Thailand': 'TH',
 'Tajikistan': 'TJ',
 'Tokelau': 'TK',
 'Turkmenistan': 'TM',
 'Timor-Leste': 'TL',
 'Tonga': 'TO',
 'Trinidad and Tobago': 'TT',
 'Tunisia': 'TN',
 'Turkey': 'TR',
 'Tuvalu': 'TV',
 'Taiwan, Province of China': 'TW',
 'Tanzania, United Republic of': 'TZ',
 'Uganda': 'UG',
 'Ukraine': 'UA',
 'United States Minor Outlying Islands': 'UM',
 'Uruguay': 'UY',
 'United States': 'US',
 'Uzbekistan': 'UZ',
 'Holy See (Vatican City State)': 'VA',
 'Saint Vincent and the Grenadines': 'VC',
 'Venezuela, Bolivarian Republic of': 'VE',
 'Virgin Islands, British': 'VG',
 'Virgin Islands, U.S.': 'VI',
 'Viet Nam': 'VN',
 'Vanuatu': 'VU',
 'Wallis and Futuna': 'WF',
 'Samoa': 'WS',
 'Yemen': 'YE',
 'South Africa': 'ZA',
 'Zambia': 'ZM',
 'Zimbabwe': 'ZW',
 'Wales': 'GB',
 'England': 'GB',
 'Scotland': 'GB',
 'Russia': 'RU',
 'Domincan Republic': 'DO',
 'USA': 'US',
 'Macedonia': 'MK',
 'United States of America': 'US',
 'Democratic Republic of Congo': 'CD',
 'Republic of Korea': 'KR',
 "Democratic People's Republic of Korea": 'KP',
 'Tanzania': 'TZ',
 'Iran': 'IR',
 'The Republic of North Macedonia': 'MK',
 'Micronesia (Federated States of)': 'FM',
 'State of Palestine': 'PS',
 'Moldova': 'MD',
 'Bolivia (Plurinational State of)': 'BO',
 'Democratic Republic of the Congo': 'CD',
 'Czech Republic': 'CZ',
 'Venezuela': 'VE',
 "Cote d'Ivoire": 'CI',
 'Vatican': 'VA',
 'Republic of Cyprus': 'CY',
 'Republic of the Congo': 'CG',
 'Ivory Coast': 'CI',
 'Sahrawi Arab Democratic Republic': 'EH',
 'São Tomé and Príncipe': 'ST',
 'Bolivia': 'BO',
 'Taiwan': 'TW',
 'Federated States of Micronesia': 'FM',
 'South Korea': 'KR',
 'South Vietnam': 'VN',
 'Holy See': 'VA',
 'Brunei': 'BN',
 'Palestine': 'PN',
 'Syria': 'SY',
 'Kosovo': 'XK',
 'Malagasy Republic': 'MG',
 'Yugoslavia': 'YU',
 'North Korea': 'KP',
 'Laos': 'LA',
 'Ceylon': 'LK',
 'Transjordan': 'JO',
 'Korea (Rep. of)': 'KR',
 'Nepal (Republic of)': 'NP',
 'Iran (Islamic Republic of)': 'IR',
 'Dominican Rep.': 'DO',
 'Dem. Rep. of the Congo': 'CD',
 'Central African Rep.': 'CF',
 "Dem. People's Rep. of Korea": 'KP',
 'Micronesia': 'FM',
 'Lao P.D.R.': 'LA',
 'Congo (Rep. of the)': 'CG',
 'Macau': 'MO',
 'Vietnam': 'VN',
 'Myanmar [Burma]': 'MM',
 'Netherlands Antilles': 'NL',
 'Cape Verde': 'CV',
 'British Virgin Islands': 'VG',
 'eSwatini': 'SZ',
 'Republic of Congo': 'CG',
 'Caribbean Netherlands': 'BQ',
 'Curacao': 'CW',
 'Sint Maarten': 'SX',
 'Saint-Martin': 'MF',
 'Bailiwick of Guernsey': 'GG',
 'Bailiwick of Jersey': 'JE',
 'East Timor': 'TL',
 'Reunion': 'RE',
 'Vatican City': 'VA'}

In [6]:
cd = os.getcwd()
prd = os.path.dirname(cd)
prd

'/home/chidurah/Projects/Surveillance'

In [7]:
datapath = os.path.join(prd, "Surveillance Data\\data.csv")
datapath

'/home/chidurah/Projects/Surveillance/Surveillance Data\\data.csv'

In [8]:
sur = pd.read_csv("../Surveillance Data/data.csv")

In [9]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,1 | R&D lab,NaN,103 | India,1999.0,NaN,NaN
1,5 | Overseas Office,10 | Subsidiary,93 | Hong Kong,2000.0,NaN,NaN
2,10 | Subsidiary,NaN,93 | Hong Kong,2000.0,NaN,NaN
3,5 | Overseas Office,10 | Subsidiary,228 | United States,2001.0,NaN,NaN
4,10 | Subsidiary,NaN,52 | Cyprus,2001.0,NaN,NaN
...,...,...,...,...,...,...
2456,13 | Cable Terrestrial,NaN,188 | Russia,NaN,NaN,NaN
2457,13 | Cable Terrestrial,NaN,123 | Kazakhstan,NaN,NaN,NaN
2458,13 | Cable Terrestrial,NaN,103 | India,NaN,NaN,NaN
2459,13 | Cable Terrestrial,NaN,143 | Myanmar [Burma],NaN,NaN,NaN
2460,13 | Cable Terrestrial,NaN,236 | Vietnam,NaN,NaN,NaN

In [10]:
sur = sur.dropna(subset = ["year_commenced", "country_id"])

In [11]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,1 | R&D lab,NaN,103 | India,1999.0,NaN,NaN
1,5 | Overseas Office,10 | Subsidiary,93 | Hong Kong,2000.0,NaN,NaN
2,10 | Subsidiary,NaN,93 | Hong Kong,2000.0,NaN,NaN
3,5 | Overseas Office,10 | Subsidiary,228 | United States,2001.0,NaN,NaN
4,10 | Subsidiary,NaN,52 | Cyprus,2001.0,NaN,NaN
...,...,...,...,...,...,...
1146,3 | Research partnership,NaN,123 | Kazakhstan,2019.0,NaN,NaN
1147,25 | Facial recognition,NaN,230 | Uzbekistan,2019.0,6 | Surveillance,5 | Chinese state loan
1148,11 | Smart cities,NaN,213 | Thailand,2019.0,2 | Smart cities,NaN
1149,3 | Research partnership,7 | Investment or joint venture,29 | Brazil,2020.0,NaN,NaN
1150,9 | Commercial partnership,NaN,228 | United States,2020.0,NaN,NaN

In [12]:
sur = sur.reset_index(drop = True)

In [13]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,1 | R&D lab,NaN,103 | India,1999.0,NaN,NaN
1,5 | Overseas Office,10 | Subsidiary,93 | Hong Kong,2000.0,NaN,NaN
2,10 | Subsidiary,NaN,93 | Hong Kong,2000.0,NaN,NaN
3,5 | Overseas Office,10 | Subsidiary,228 | United States,2001.0,NaN,NaN
4,10 | Subsidiary,NaN,52 | Cyprus,2001.0,NaN,NaN
...,...,...,...,...,...,...
1145,3 | Research partnership,NaN,123 | Kazakhstan,2019.0,NaN,NaN
1146,25 | Facial recognition,NaN,230 | Uzbekistan,2019.0,6 | Surveillance,5 | Chinese state loan
1147,11 | Smart cities,NaN,213 | Thailand,2019.0,2 | Smart cities,NaN
1148,3 | Research partnership,7 | Investment or joint venture,29 | Brazil,2020.0,NaN,NaN
1149,9 | Commercial partnership,NaN,228 | United States,2020.0,NaN,NaN

In [14]:
sur["year_commenced"] = sur["year_commenced"].astype(int)

In [15]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,1 | R&D lab,NaN,103 | India,1999,NaN,NaN
1,5 | Overseas Office,10 | Subsidiary,93 | Hong Kong,2000,NaN,NaN
2,10 | Subsidiary,NaN,93 | Hong Kong,2000,NaN,NaN
3,5 | Overseas Office,10 | Subsidiary,228 | United States,2001,NaN,NaN
4,10 | Subsidiary,NaN,52 | Cyprus,2001,NaN,NaN
...,...,...,...,...,...,...
1145,3 | Research partnership,NaN,123 | Kazakhstan,2019,NaN,NaN
1146,25 | Facial recognition,NaN,230 | Uzbekistan,2019,6 | Surveillance,5 | Chinese state loan
1147,11 | Smart cities,NaN,213 | Thailand,2019,2 | Smart cities,NaN
1148,3 | Research partnership,7 | Investment or joint venture,29 | Brazil,2020,NaN,NaN
1149,9 | Commercial partnership,NaN,228 | United States,2020,NaN,NaN

In [16]:
def drop_num(x):
    entry = x
    if (type(entry) != float):
        entry = entry.split(" | ")
        if (len(entry) > 1):
            entry = entry[1]
    return entry

In [17]:
def remove_num(data, col_names):
    for col_name in col_names:
        col = data[col_name]
        n_col = col.apply(lambda x: drop_num(x))
        data[col_name] = n_col
    return data

In [18]:
sur = remove_num(sur, ["infrastructure_type_id", "secondary_infrastructure_type_id", "country_id", "Primary topic", "Secondary (if needed)"])

In [19]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,R&D lab,NaN,India,1999,NaN,NaN
1,Overseas Office,Subsidiary,Hong Kong,2000,NaN,NaN
2,Subsidiary,NaN,Hong Kong,2000,NaN,NaN
3,Overseas Office,Subsidiary,United States,2001,NaN,NaN
4,Subsidiary,NaN,Cyprus,2001,NaN,NaN
...,...,...,...,...,...,...
1145,Research partnership,NaN,Kazakhstan,2019,NaN,NaN
1146,Facial recognition,NaN,Uzbekistan,2019,Surveillance,Chinese state loan
1147,Smart cities,NaN,Thailand,2019,Smart cities,NaN
1148,Research partnership,Investment or joint venture,Brazil,2020,NaN,NaN
1149,Commercial partnership,NaN,United States,2020,NaN,NaN

In [20]:
from Human_Rights_Lab import CountryCodes

In [21]:
sur = CountryCodes(sur, "country_id", name_to_alpha_2)

In [22]:
sur

,infrastructure_type_id,secondary_infrastructure_type_id,country_id,year_commenced,Primary topic,Secondary (if needed)
0,R&D lab,NaN,IN,1999,NaN,NaN
1,Overseas Office,Subsidiary,HK,2000,NaN,NaN
2,Subsidiary,NaN,HK,2000,NaN,NaN
3,Overseas Office,Subsidiary,US,2001,NaN,NaN
4,Subsidiary,NaN,CY,2001,NaN,NaN
...,...,...,...,...,...,...
1145,Research partnership,NaN,KZ,2019,NaN,NaN
1146,Facial recognition,NaN,UZ,2019,Surveillance,Chinese state loan
1147,Smart cities,NaN,TH,2019,Smart cities,NaN
1148,Research partnership,Investment or joint venture,BR,2020,NaN,NaN
1149,Commercial partnership,NaN,US,2020,NaN,NaN

In [23]:
counts = sur["infrastructure_type_id"].value_counts()

In [24]:
def make_year_country_table(data, year_col, country_col):
    yc = pd.DataFrame(columns = [year_col, country_col])
    years = np.unique(data[year_col])
    countries = np.unique(data[country_col])
    index = 0
    for year in years:
        for country in countries:
            yc.loc[index] = [year, country]
            index += 1
    return yc

In [25]:
instances = make_year_country_table(sur, "year_commenced", "country_id")

In [26]:
instances

      year_commenced country_id
0               1999         AE
1               1999         AF
2               1999         AM
3               1999         AO
4               1999         AQ
...              ...        ...
3119            2020         VU
3120            2020         WS
3121            2020         ZA
3122            2020         ZM
3123            2020         ZW

[3124 rows x 2 columns]

In [27]:
def add_infras(data, infras):
    for infra in infras:
        data[infra] = np.zeros(len(data))
    return data

In [28]:
instances = add_infras(instances, np.unique(sur["infrastructure_type_id"]))
instances = add_infras(instances, np.unique(sur["Primary topic"].dropna()))

In [29]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,1999,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1999,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1999,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1999,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1999,AQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3120,2020,WS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3121,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3122,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3123,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
instances["country_id"]

0       AE
1       AF
2       AM
3       AO
4       AQ
        ..
3119    VU
3120    WS
3121    ZA
3122    ZM
3123    ZW
Name: country_id, Length: 3124, dtype: object

In [31]:
def get_counts(x, count_data, infra_col, year_col, country_col):
    country = x[country_col]
    year = x[year_col]
    filtered = count_data.loc[count_data[year_col] == year]
    filtered = filtered.loc[filtered[country_col] == country]
    values = filtered[infra_col].dropna()
    values = values.value_counts()
    for index in values.index:
        x[index] = x[index] + values[index]
    return x

In [32]:
def counts(instance_data, count_data, infra_col, year_col, country_col):
    instance_data = instance_data.apply(lambda x: get_counts(x, count_data, infra_col, year_col, country_col), axis = 1)
    return instance_data

In [33]:
#instances = counts(instances, sur, "infrastructure_type_id", "year_commenced", "country_id")

In [34]:
#instances

In [35]:
def add_infra_counts(instance_data, count_data, infra_cols, year_col, country_col):
    for infra_col in infra_cols:
        instance_data = counts(instance_data, count_data, infra_col, year_col, country_col)
    return instance_data

In [36]:
instances = add_infra_counts(instances, sur, ["infrastructure_type_id", "secondary_infrastructure_type_id", "Primary topic", "Secondary (if needed)"], "year_commenced", "country_id")
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,1999,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1999,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1999,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1999,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1999,AQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3120,2020,WS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3121,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3122,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3123,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
from country_dicts import alpha_2_to_name
instances = CountryCodes(instances, "country_id", alpha_2_to_name)

In [38]:
cd = os.getcwd()
prd = os.path.dirname(cd)
prd

'/home/chidurah/Projects/Surveillance'

In [39]:
destination_path = os.path.join(prd, "Surveillance Output\\surveillancecategorized.csv")
destination_path

'/home/chidurah/Projects/Surveillance/Surveillance Output\\surveillancecategorized.csv'

In [40]:
instances.to_csv(destination_path)

In [41]:
v_modified_path = os.path.join(prd, "Surveillance Data\\V-Dem Indicators Modified.csv")
v_modified_path
v_indicator_path = os.path.join(prd, "Surveillance Data\\V-Dem Indicators.csv")
v_indicator_path

'/home/chidurah/Projects/Surveillance/Surveillance Data\\V-Dem Indicators.csv'

In [42]:
v_modified = pd.read_csv("../Surveillance Data/V-Dem Indicators Modified.csv")
v_indicators = pd.read_csv("../Surveillance Data/V-Dem Indicators.csv")

In [43]:
v_modified

,country_name,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2smgovfilcap,v2smgovfilcap_ord,v2smgovfilprc,v2smgovfilprc_ord,v2smgovshutcap,...,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
0,Afghanistan,2021,0.158,0.043,0.048,-0.215,2,-0.999,2,-0.965,...,7,NaN,-1.142,-1.634,-2.530,2.0,1.0,-1.0,6775.201,3884.685
1,Albania,2021,0.489,0.410,0.302,-0.183,2,-0.004,3,-1.038,...,3,9.0,-0.556,-0.003,0.109,0.0,9.0,9.0,3489.639,309.720
2,Algeria,2021,0.281,0.138,0.111,1.829,3,-1.680,1,1.560,...,6,6.0,-0.614,-0.621,-0.876,1.0,3.0,2.0,52143.253,4491.912
3,Angola,2021,0.342,0.168,0.093,0.225,2,1.048,3,0.172,...,6,5.0,-0.655,-1.059,-0.711,4.0,2.0,-2.0,16911.415,3137.989
4,Argentina,2021,0.811,0.657,0.551,-0.294,2,2.367,4,-1.401,...,2,10.0,-0.401,-0.357,-0.106,0.0,9.0,9.0,78294.101,4740.302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Venezuela,2021,0.218,0.064,0.166,2.018,3,-2.101,1,0.824,...,7,1.0,-1.606,-1.852,-1.526,4.0,1.0,-3.0,3113.377,2618.458
159,Vietnam,2021,0.157,0.112,0.168,1.861,3,-2.071,1,0.879,...,7,4.0,-0.286,0.278,-0.115,7.0,0.0,-7.0,71416.028,10268.110
160,Yemen,2021,0.114,0.035,0.067,1.499,3,-2.138,1,1.235,...,7,2.0,-1.652,-2.304,-2.588,NaN,NaN,NaN,4498.425,3020.905
161,Zambia,2021,0.411,0.318,0.270,1.260,3,0.157,3,2.340,...,4,8.0,-0.753,-0.817,0.060,0.0,6.0,6.0,5382.952,1862.477
162,Zimbabwe,2021,0.291,0.194,0.221,0.978,3,-0.350,2,1.017,...,6,2.0,-1.258,-1.243,-1.027,1.0,5.0,4.0,4870.709,1566.385

In [44]:
v_indicators

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,e_pefeliex,e_peinfmor,e_pelifeex,e_pematmor,e_wb_pop,e_civil_war,e_miinteco,e_miinterc,e_pt_coup,e_pt_coup_attempts
0,Mexico,MEX,3,1789,1789-12-31,1,1,Viceroyalty of New Spain,1789,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1,Mexico,MEX,3,1790,1790-12-31,1,1,Viceroyalty of New Spain,1789,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,Mexico,MEX,3,1791,1791-12-31,1,1,Viceroyalty of New Spain,1789,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,Mexico,MEX,3,1792,1792-12-31,1,1,Viceroyalty of New Spain,1789,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
4,Mexico,MEX,3,1793,1793-12-31,1,1,Viceroyalty of New Spain,1789,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27550,Piedmont-Sardinia,SPD,373,1857,1857-12-31,1,1,Kingdom of Piedmont-Sardinia,1789,1861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27551,Piedmont-Sardinia,SPD,373,1858,1858-12-31,1,1,Kingdom of Piedmont-Sardinia,1789,1861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27552,Piedmont-Sardinia,SPD,373,1859,1859-12-31,1,1,Kingdom of Piedmont-Sardinia [incorporates Lom...,1789,1861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27553,Piedmont-Sardinia,SPD,373,1860,1860-12-31,1,1,NaN,1789,1861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27554,Piedmont-Sardinia,SPD,373,1861,1861-12-31,1,1,Kingdom of Piedmont-Sardinia,1789,1861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
def Between(x, year_col, begin, end):
    if int(x[year_col]) >= begin and int(x[year_col]) <= end:
        return True
    else:
        return False
    
def YearCutoff(data, year_col, begin, end):
    locs = data.apply(lambda x: Between(x, year_col, begin, end), axis = 1)
    data = data[locs]
    data = data.reset_index(drop = True)
    return data

In [46]:
instances = YearCutoff(instances, "year_commenced", 2010, 2020)
v_indicators = YearCutoff(v_indicators, "year", 2010, 2020)

In [47]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,2010,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010,Armenia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010,Antarctica,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,2020,Vanuatu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1558,2020,Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1559,2020,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1560,2020,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1561,2020,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
v_indicators

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,e_pefeliex,e_peinfmor,e_pelifeex,e_pematmor,e_wb_pop,e_civil_war,e_miinteco,e_miinterc,e_pt_coup,e_pt_coup_attempts
0,Mexico,MEX,3,2010,12/31/2010,0,1,United Mexican States,1789,2022,...,NaN,17.4,75.3,47.0,114092961.0,NaN,NaN,NaN,0.0,0.0
1,Mexico,MEX,3,2011,12/31/2011,0,1,United Mexican States,1789,2022,...,NaN,16.9,75.5,NaN,115695468.0,NaN,NaN,NaN,0.0,0.0
2,Mexico,MEX,3,2012,12/31/2012,0,1,United Mexican States,1789,2022,...,NaN,16.4,75.7,NaN,117274156.0,NaN,NaN,NaN,0.0,0.0
3,Mexico,MEX,3,2013,12/31/2013,0,1,United Mexican States,1789,2022,...,NaN,15.9,75.5,49.0,118827158.0,NaN,NaN,NaN,0.0,0.0
4,Mexico,MEX,3,2014,12/31/2014,0,1,United Mexican States,1789,2022,...,NaN,15.4,75.6,NaN,120355137.0,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,Zanzibar,ZZB,236,2016,12/31/2016,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964,Zanzibar,ZZB,236,2017,12/31/2017,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965,Zanzibar,ZZB,236,2018,12/31/2018,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,Zanzibar,ZZB,236,2019,12/31/2019,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,Zanzibar,ZZB,236,2020,12/31/2020,0,1,"Zanzibar, semi-autonomous region of Tanzania",1856,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,2010,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010,Armenia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010,Antarctica,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,2020,Vanuatu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1558,2020,Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1559,2020,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1560,2020,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1561,2020,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
def DropCountriesRow(x, countries, country_col):
    if (x[country_col] in countries):
        return False
    else:
        return True

In [51]:
def DropCountries(data, countries, country_col):
    locs = data.apply(lambda x: DropCountriesRow(x, countries, country_col), axis = 1)
    data = data[locs]
    data = data.reset_index(drop = True)
    return data

In [52]:
v_indicators = DropCountries(v_indicators, ["SML", "ZZB"], "country_text_id")
v_indicators

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,e_pefeliex,e_peinfmor,e_pelifeex,e_pematmor,e_wb_pop,e_civil_war,e_miinteco,e_miinterc,e_pt_coup,e_pt_coup_attempts
0,Mexico,MEX,3,2010,12/31/2010,0,1,United Mexican States,1789,2022,...,NaN,17.40,75.3,47.0,114092961.0,NaN,NaN,NaN,0.0,0.0
1,Mexico,MEX,3,2011,12/31/2011,0,1,United Mexican States,1789,2022,...,NaN,16.90,75.5,NaN,115695468.0,NaN,NaN,NaN,0.0,0.0
2,Mexico,MEX,3,2012,12/31/2012,0,1,United Mexican States,1789,2022,...,NaN,16.40,75.7,NaN,117274156.0,NaN,NaN,NaN,0.0,0.0
3,Mexico,MEX,3,2013,12/31/2013,0,1,United Mexican States,1789,2022,...,NaN,15.90,75.5,49.0,118827158.0,NaN,NaN,NaN,0.0,0.0
4,Mexico,MEX,3,2014,12/31/2014,0,1,United Mexican States,1789,2022,...,NaN,15.40,75.6,NaN,120355137.0,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,Hungary,HUN,210,2016,12/31/2016,0,1,Hungary,1789,2022,...,NaN,4.83,76.3,NaN,9814023.0,NaN,NaN,NaN,0.0,0.0
1942,Hungary,HUN,210,2017,12/31/2017,0,1,Hungary,1789,2022,...,NaN,4.54,76.3,NaN,9787966.0,NaN,NaN,NaN,0.0,0.0
1943,Hungary,HUN,210,2018,12/31/2018,0,1,Hungary,1789,2022,...,NaN,4.27,76.3,NaN,9775564.0,NaN,NaN,NaN,0.0,0.0
1944,Hungary,HUN,210,2019,12/31/2019,0,1,Hungary,1789,2022,...,NaN,4.12,76.6,NaN,9771141.0,NaN,NaN,NaN,0.0,0.0
1945,Hungary,HUN,210,2020,12/31/2020,0,1,Hungary,1789,2022,...,NaN,3.99,75.8,NaN,9750149.0,NaN,NaN,NaN,0.0,0.0

In [53]:
import country_dicts
from country_dicts import alpha_3_to_alpha_2

In [54]:
v_indicators = CountryCodes(v_indicators, "country_text_id", alpha_3_to_alpha_2)

In [55]:
v_indicators
isos = v_indicators["country_text_id"]

In [56]:
demo_columns = list(v_modified.columns)
indicator_columns = list(v_indicators.columns)
demo_columns
indicator_columns

['country_name',
 'country_text_id',
 'country_id',
 'year',
 'historical_date',
 'project',
 'historical',
 'histname',
 'codingstart',
 'codingend',
 'codingstart_contemp',
 'codingend_contemp',
 'codingstart_hist',
 'codingend_hist',
 'gapstart1',
 'gapstart2',
 'gapstart3',
 'gapend1',
 'gapend2',
 'gapend3',
 'gap_index',
 'COWcode',
 'v2x_polyarchy',
 'v2x_polyarchy_codelow',
 'v2x_polyarchy_codehigh',
 'v2x_polyarchy_sd',
 'v2x_libdem',
 'v2x_libdem_codelow',
 'v2x_libdem_codehigh',
 'v2x_libdem_sd',
 'v2x_partipdem',
 'v2x_partipdem_codelow',
 'v2x_partipdem_codehigh',
 'v2x_partipdem_sd',
 'v2x_delibdem',
 'v2x_delibdem_codelow',
 'v2x_delibdem_codehigh',
 'v2x_delibdem_sd',
 'v2x_egaldem',
 'v2x_egaldem_codelow',
 'v2x_egaldem_codehigh',
 'v2x_egaldem_sd',
 'v2smgovfilcap',
 'v2smgovfilcap_codelow',
 'v2smgovfilcap_codehigh',
 'v2smgovfilcap_sd',
 'v2smgovfilcap_osp',
 'v2smgovfilcap_osp_codelow',
 'v2smgovfilcap_osp_codehigh',
 'v2smgovfilcap_osp_sd',
 'v2smgovfilcap_ord',
 'v2smgovfilcap_ord_codelow',
 'v2smgovfilcap_ord_codehigh',
 'v2smgovfilcap_mean',
 'v2smgovfilcap_nr',
 'v2smgovfilprc',
 'v2smgovfilprc_codelow',
 'v2smgovfilprc_codehigh',
 'v2smgovfilprc_sd',
 'v2smgovfilprc_osp',
 'v2smgovfilprc_osp_codelow',
 'v2smgovfilprc_osp_codehigh',
 'v2smgovfilprc_osp_sd',
 'v2smgovfilprc_ord',
 'v2smgovfilprc_ord_codelow',
 'v2smgovfilprc_ord_codehigh',
 'v2smgovfilprc_mean',
 'v2smgovfilprc_nr',
 'v2smgovshutcap',
 'v2smgovshutcap_codelow',
 'v2smgovshutcap_codehigh',
 'v2smgovshutcap_sd',
 'v2smgovshutcap_osp',
 'v2smgovshutcap_osp_codelow',
 'v2smgovshutcap_osp_codehigh',
 'v2smgovshutcap_osp_sd',
 'v2smgovshutcap_ord',
 'v2smgovshutcap_ord_codelow',
 'v2smgovshutcap_ord_codehigh',
 'v2smgovshutcap_mean',
 'v2smgovshutcap_nr',
 'v2smgovshut',
 'v2smgovshut_codelow',
 'v2smgovshut_codehigh',
 'v2smgovshut_sd',
 'v2smgovshut_osp',
 'v2smgovshut_osp_codelow',
 'v2smgovshut_osp_codehigh',
 'v2smgovshut_osp_sd',
 'v2smgovshut_ord',
 'v2smgovshut_ord_codelow',
 'v2smgovshut_ord_codehigh',
 'v2smgovshut_mean',
 'v2smgovshut_nr',
 'v2smgovsm',
 'v2smgovsm_codelow',
 'v2smgovsm_codehigh',
 'v2smgovsm_sd',
 'v2smgovsm_osp',
 'v2smgovsm_osp_codelow',
 'v2smgovsm_osp_codehigh',
 'v2smgovsm_osp_sd',
 'v2smgovsm_ord',
 'v2smgovsm_ord_codelow',
 'v2smgovsm_ord_codehigh',
 'v2smgovsm_mean',
 'v2smgovsm_nr',
 'v2smgovsmalt',
 'v2smgovsmalt_codelow',
 'v2smgovsmalt_codehigh',
 'v2smgovsmalt_sd',
 'v2smgovsmalt_osp',
 'v2smgovsmalt_osp_codelow',
 'v2smgovsmalt_osp_codehigh',
 'v2smgovsmalt_osp_sd',
 'v2smgovsmalt_ord',
 'v2smgovsmalt_ord_codelow',
 'v2smgovsmalt_ord_codehigh',
 'v2smgovsmalt_mean',
 'v2smgovsmalt_nr',
 'v2smgovsmmon',
 'v2smgovsmmon_codelow',
 'v2smgovsmmon_codehigh',
 'v2smgovsmmon_sd',
 'v2smgovsmmon_osp',
 'v2smgovsmmon_osp_codelow',
 'v2smgovsmmon_osp_codehigh',
 'v2smgovsmmon_osp_sd',
 'v2smgovsmmon_ord',
 'v2smgovsmmon_ord_codelow',
 'v2smgovsmmon_ord_codehigh',
 'v2smgovsmmon_mean',
 'v2smgovsmmon_nr',
 'v2smgovsmcenprc',
 'v2smgovsmcenprc_codelow',
 'v2smgovsmcenprc_codehigh',
 'v2smgovsmcenprc_sd',
 'v2smgovsmcenprc_osp',
 'v2smgovsmcenprc_osp_codelow',
 'v2smgovsmcenprc_osp_codehigh',
 'v2smgovsmcenprc_osp_sd',
 'v2smgovsmcenprc_ord',
 'v2smgovsmcenprc_ord_codelow',
 'v2smgovsmcenprc_ord_codehigh',
 'v2smgovsmcenprc_mean',
 'v2smgovsmcenprc_nr',
 'v2smgovcapsec',
 'v2smgovcapsec_codelow',
 'v2smgovcapsec_codehigh',
 'v2smgovcapsec_sd',
 'v2smgovcapsec_osp',
 'v2smgovcapsec_osp_codelow',
 'v2smgovcapsec_osp_codehigh',
 'v2smgovcapsec_osp_sd',
 'v2smgovcapsec_ord',
 'v2smgovcapsec_ord_codelow',
 'v2smgovcapsec_ord_codehigh',
 'v2smgovcapsec_mean',
 'v2smgovcapsec_nr',
 'v2smpolcap',
 'v2smpolcap_codelow',
 'v2smpolcap_codehigh',
 'v2smpolcap_sd',
 'v2smpolcap_osp',
 'v2smpolcap_osp_codelow',
 'v2smpolcap_osp_codehigh',
 'v2smpolcap_osp_sd',
 'v2smpolcap_ord',
 'v2smpolcap_ord_codelow',
 'v2smpolcap_ord_codehigh',
 'v2smpolcap_mean',
 'v2smpolcap_nr',
 'v2smregcon',
 'v2smregcon_codelow',
 'v2smregcon_codehigh',
 'v2smregcon_sd',
 'v2smregcon_osp',
 'v2smregcon_osp_codelow',
 'v2smregcon_osp_codehigh',
 'v2smregcon_osp_sd',
 'v2smregcon_ord',
 'v2smregcon_ord_codelow',
 'v2smregcon_ord_codehigh',
 'v2smregcon_mean',
 'v2smregcon_nr',
 'v2smprivex',
 'v2smprivex_codelow',
 'v2smprivex_codehigh',
 'v2smprivex_sd',
 'v2smprivex_osp',
 'v2smprivex_osp_codelow',
 'v2smprivex_osp_codehigh',
 'v2smprivex_osp_sd',
 'v2smprivex_ord',
 'v2smprivex_ord_codelow',
 'v2smprivex_ord_codehigh',
 'v2smprivex_mean',
 'v2smprivex_nr',
 'v2smprivcon',
 'v2smprivcon_codelow',
 'v2smprivcon_codehigh',
 'v2smprivcon_sd',
 'v2smprivcon_osp',
 'v2smprivcon_osp_codelow',
 'v2smprivcon_osp_codehigh',
 'v2smprivcon_osp_sd',
 'v2smprivcon_ord',
 'v2smprivcon_ord_codelow',
 'v2smprivcon_ord_codehigh',
 'v2smprivcon_mean',
 'v2smprivcon_nr',
 'v2smregcap',
 'v2smregcap_codelow',
 'v2smregcap_codehigh',
 'v2smregcap_sd',
 'v2smregcap_osp',
 'v2smregcap_osp_codelow',
 'v2smregcap_osp_codehigh',
 'v2smregcap_osp_sd',
 'v2smregcap_ord',
 'v2smregcap_ord_codelow',
 'v2smregcap_ord_codehigh',
 'v2smregcap_mean',
 'v2smregcap_nr',
 'v2smregapp',
 'v2smregapp_codelow',
 'v2smregapp_codehigh',
 'v2smregapp_sd',
 'v2smregapp_osp',
 'v2smregapp_osp_codelow',
 'v2smregapp_osp_codehigh',
 'v2smregapp_osp_sd',
 'v2smregapp_ord',
 'v2smregapp_ord_codelow',
 'v2smregapp_ord_codehigh',
 'v2smregapp_mean',
 'v2smregapp_nr',
 'v2smlawpr',
 'v2smlawpr_codelow',
 'v2smlawpr_codehigh',
 'v2smlawpr_sd',
 'v2smlawpr_osp',
 'v2smlawpr_osp_codelow',
 'v2smlawpr_osp_codehigh',
 'v2smlawpr_osp_sd',
 'v2smlawpr_ord',
 'v2smlawpr_ord_codelow',
 'v2smlawpr_ord_codehigh',
 'v2smlawpr_mean',
 'v2smlawpr_nr',
 'v2smdefabu',
 'v2smdefabu_codelow',
 'v2smdefabu_codehigh',
 'v2smdefabu_sd',
 'v2smdefabu_osp',
 'v2smdefabu_osp_codelow',
 'v2smdefabu_osp_codehigh',
 'v2smdefabu_osp_sd',
 'v2smdefabu_ord',
 'v2smdefabu_ord_codelow',
 'v2smdefabu_ord_codehigh',
 'v2smdefabu_mean',
 'v2smdefabu_nr',
 'v2smonex',
 'v2smonex_codelow',
 'v2smonex_codehigh',
 'v2smonex_sd',
 'v2smonex_osp',
 'v2smonex_osp_codelow',
 'v2smonex_osp_codehigh',
 'v2smonex_osp_sd',
 'v2smonex_ord',
 'v2smonex_ord_codelow',
 'v2smonex_ord_codehigh',
 'v2smonex_mean',
 'v2smonex_nr',
 'v2smonper',
 'v2smonper_codelow',
 'v2smonper_codehigh',
 'v2smonper_sd',
 'v2smonper_osp',
 'v2smonper_osp_codelow',
 'v2smonper_osp_codehigh',
 'v2smonper_osp_sd',
 'v2smonper_ord',
 'v2smonper_ord_codelow',
 'v2smonper_ord_codehigh',
 'v2smonper_mean',
 'v2smonper_nr',
 'v2smmefra',
 'v2smmefra_codelow',
 'v2smmefra_codehigh',
 'v2smmefra_sd',
 'v2smmefra_osp',
 'v2smmefra_osp_codelow',
 'v2smmefra_osp_codehigh',
 'v2smmefra_osp_sd',
 'v2smmefra_ord',
 'v2smmefra_ord_codelow',
 'v2smmefra_ord_codehigh',
 'v2smmefra_mean',
 'v2smmefra_nr',
 'v2smorgviol',
 'v2smorgviol_codelow',
 'v2smorgviol_codehigh',
 'v2smorgviol_sd',
 'v2smorgviol_osp',
 'v2smorgviol_osp_codelow',
 'v2smorgviol_osp_codehigh',
 'v2smorgviol_osp_sd',
 'v2smorgviol_ord',
 'v2smorgviol_ord_codelow',
 'v2smorgviol_ord_codehigh',
 'v2smorgviol_mean',
 'v2smorgviol_nr',
 'v2smorgavgact',
 'v2smorgavgact_codelow',
 'v2smorgavgact_codehigh',
 'v2smorgavgact_sd',
 'v2smorgavgact_osp',
 'v2smorgavgact_osp_codelow',
 'v2smorgavgact_osp_codehigh',
 'v2smorgavgact_osp_sd',
 'v2smorgavgact_ord',
 'v2smorgavgact_ord_codelow',
 'v2smorgavgact_ord_codehigh',
 'v2smorgavgact_mean',
 'v2smorgavgact_nr',
 'v2smorgelitact',
 'v2smorgelitact_codelow',
 'v2smorgelitact_codehigh',
 'v2smorgelitact_sd',
 'v2smorgelitact_osp',
 'v2smorgelitact_osp_codelow',
 'v2smorgelitact_osp_codehigh',
 'v2smorgelitact_osp_sd',
 'v2smorgelitact_ord',
 'v2smorgelitact_ord_codelow',
 'v2smorgelitact_ord_codehigh',
 'v2smorgelitact_mean',
 'v2smorgelitact_nr',
 'v2smcamp',
 'v2smcamp_codelow',
 'v2smcamp_codehigh',
 'v2smcamp_sd',
 'v2smcamp_osp',
 'v2smcamp_osp_codelow',
 'v2smcamp_osp_codehigh',
 'v2smcamp_osp_sd',
 'v2smcamp_ord',
 'v2smcamp_ord_codelow',
 'v2smcamp_ord_codehigh',
 'v2smcamp_mean',
 'v2smcamp_nr',
 'v2smarrest',
 'v2smarrest_codelow',
 'v2smarrest_codehigh',
 'v2smarrest_sd',
 'v2smarrest_osp',
 'v2smarrest_osp_codelow',
 'v2smarrest_osp_codehigh',
 'v2smarrest_osp_sd',
 'v2smarrest_ord',
 'v2smarrest_ord_codelow',
 'v2smarrest_ord_codehigh',
 'v2smarrest_mean',
 'v2smarrest_nr',
 'v2smpolsoc',
 'v2smpolsoc_codelow',
 'v2smpolsoc_codehigh',
 'v2smpolsoc_sd',
 'v2smpolsoc_osp',
 'v2smpolsoc_osp_codelow',
 'v2smpolsoc_osp_codehigh',
 'v2smpolsoc_osp_sd',
 'v2smpolsoc_ord',
 'v2smpolsoc_ord_codelow',
 'v2smpolsoc_ord_codehigh',
 'v2smpolsoc_mean',
 'v2smpolsoc_nr',
 'v2smpolhate',
 'v2smpolhate_codelow',
 'v2smpolhate_codehigh',
 'v2smpolhate_sd',
 'v2smpolhate_osp',
 'v2smpolhate_osp_codelow',
 'v2smpolhate_osp_codehigh',
 'v2smpolhate_osp_sd',
 'v2smpolhate_ord',
 'v2smpolhate_ord_codelow',
 'v2smpolhate_ord_codehigh',
 'v2smpolhate_mean',
 'v2smpolhate_nr',
 'v2smhargr_0',
 'v2smhargr_1',
 'v2smhargr_2',
 'v2smhargr_3',
 'v2smhargr_4',
 'v2smhargr_5',
 'v2smhargr_6',
 'v2smhargr_7',
 'v2smhargr_8',
 'v2smhargr_9',
 'v2smhargr_10',
 'v2smhargr_nr',
 'v2smorgtypes_0',
 'v2smorgtypes_1',
 'v2smorgtypes_2',
 'v2smorgtypes_3',
 'v2smorgtypes_4',
 'v2smorgtypes_5',
 'v2smorgtypes_6',
 'v2smorgtypes_7',
 'v2smorgtypes_8',
 'v2smorgtypes_9',
 'v2smorgtypes_nr',
 'v2xed_ed_inpt',
 'v2xed_ed_inpt_codelow',
 'v2xed_ed_inpt_codehigh',
 'v2xed_ed_inpt_sd',
 'v2xed_ed_poed',
 'v2xed_ed_poed_codelow',
 'v2xed_ed_poed_codehigh',
 'v2xed_ed_poed_sd',
 'v2xed_ed_inco',
 'v2xed_ed_inco_codelow',
 'v2xed_ed_inco_codehigh',
 'v2xed_ed_inco_sd',
 'v2xed_ed_cent',
 'v2xed_ed_cent_codelow',
 'v2xed_ed_cent_codehigh',
 'v2xed_ed_cent_sd',
 'v2xed_ed_ctag',
 'v2xed_ed_ctag_codelow',
 'v2xed_ed_ctag_codehigh',
 'v2xed_ed_ctag_sd',
 'v2xed_ed_con',
 'v2xed_ed_con_codelow',
 'v2xed_ed_con_codehigh',
 'v2xed_ed_con_sd',
 'v2xed_ed_dmcon',
 'v2xed_ed_dmcon_codelow',
 'v2xed_ed_dmcon_codehigh',
 'v2xed_ed_dmcon_sd',
 'v2xed_ed_ptcon',
 'v2xed_ed_ptcon_codelow',
 'v2xed_ed_ptcon_codehigh',
 'v2xed_ed_ptcon_sd',
 'v2xed_ptcon',
 'v2xed_ptcon_codelow',
 'v2xed_ptcon_codehigh',
 'v2xed_ptcon_sd',
 'v2xedvd_inpt',
 'v2xedvd_inpt_codelow',
 'v2xedvd_inpt_codehigh',
 'v2xedvd_inpt_sd',
 'v2xedvd_me_inco',
 'v2xedvd_me_inco_codelow',
 'v2xedvd_me_inco_codehigh',
 'v2xedvd_me_inco_sd',
 'v2xedvd_me_cent',
 'v2xedvd_me_cent_codelow',
 'v2xedvd_me_cent_codehigh',
 'v2xedvd_me_cent_sd',
 'v2xedvd_me_ctag',
 'v2xedvd_me_ctag_codelow',
 'v2xedvd_me_ctag_codehigh',
 'v2xedvd_me_ctag_sd',
 'v2edcentcurrlm',
 'v2edcentcurrlm_codelow',
 'v2edcentcurrlm_codehigh',
 'v2edcentcurrlm_sd',
 'v2edcentcurrlm_osp',
 'v2edcentcurrlm_osp_codelow',
 'v2edcentcurrlm_osp_codehigh',
 'v2edcentcurrlm_osp_sd',
 'v2edcentcurrlm_ord',
 'v2edcentcurrlm_ord_codelow',
 'v2edcentcurrlm_ord_codehigh',
 'v2edcentcurrlm_mean',
 'v2edcentcurrlm_nr',
 'v2edcenttxbooks',
 'v2edcenttxbooks_codelow',
 'v2edcenttxbooks_codehigh',
 'v2edcenttxbooks_sd',
 'v2edcenttxbooks_osp',
 'v2edcenttxbooks_osp_codelow',
 'v2edcenttxbooks_osp_codehigh',
 'v2edcenttxbooks_osp_sd',
 'v2edcenttxbooks_ord',
 'v2edcenttxbooks_ord_codelow',
 'v2edcenttxbooks_ord_codehigh',
 'v2edcenttxbooks_mean',
 'v2edcenttxbooks_nr',
 'v2edpoledprim',
 'v2edpoledprim_codelow',
 'v2edpoledprim_codehigh',
 'v2edpoledprim_sd',
 'v2edpoledprim_osp',
 'v2edpoledprim_osp_codelow',
 'v2edpoledprim_osp_codehigh',
 'v2edpoledprim_osp_sd',
 'v2edpoledprim_ord',
 'v2edpoledprim_ord_codelow',
 'v2edpoledprim_ord_codehigh',
 'v2edpoledprim_mean',
 'v2edpoledprim_nr',
 'v2edpoledsec',
 'v2edpoledsec_codelow',
 'v2edpoledsec_codehigh',
 'v2edpoledsec_sd',
 'v2edpoledsec_osp',
 'v2edpoledsec_osp_codelow',
 'v2edpoledsec_osp_codehigh',
 'v2edpoledsec_osp_sd',
 'v2edpoledsec_ord',
 'v2edpoledsec_ord_codelow',
 'v2edpoledsec_ord_codehigh',
 'v2edpoledsec_mean',
 'v2edpoledsec_nr',
 'v2edpoledrights',
 'v2edpoledrights_codelow',
 'v2edpoledrights_codehigh',
 'v2edpoledrights_sd',
 'v2edpoledrights_osp',
 'v2edpoledrights_osp_codelow',
 'v2edpoledrights_osp_codehigh',
 'v2edpoledrights_osp_sd',
 'v2edpoledrights_ord',
 'v2edpoledrights_ord_codelow',
 'v2edpoledrights_ord_codehigh',
 'v2edpoledrights_mean',
 'v2edpoledrights_nr',
 'v2edpatriot',
 'v2edpatriot_codelow',
 'v2edpatriot_codehigh',
 'v2edpatriot_sd',
 'v2edpatriot_osp',
 'v2edpatriot_osp_codelow',
 'v2edpatriot_osp_codehigh',
 'v2edpatriot_osp_sd',
 'v2edpatriot_ord',
 'v2edpatriot_ord_codelow',
 'v2edpatriot_ord_codehigh',
 'v2edpatriot_mean',
 'v2edpatriot_nr',
 'v2edideol',
 'v2edideol_codelow',
 'v2edideol_codehigh',
 'v2edideol_sd',
 'v2edideol_osp',
 'v2edideol_osp_codelow',
 'v2edideol_osp_codehigh',
 'v2edideol_osp_sd',
 'v2edideol_ord',
 'v2edideol_ord_codelow',
 'v2edideol_ord_codehigh',
 'v2edideol_mean',
 'v2edideol_nr',
 'v2edideolch_rec',
 'v2edideolch_rec_codelow',
 'v2edideolch_rec_codehigh',
 'v2edideolch_rec_sd',
 'v2edideolch_rec_osp',
 'v2edideolch_rec_osp_codelow',
 'v2edideolch_rec_osp_codehigh',
 'v2edideolch_rec_osp_sd',
 'v2edideolch_rec_ord',
 'v2edideolch_rec_ord_codelow',
 'v2edideolch_rec_ord_codehigh',
 'v2edideolch_rec_mean',
 'v2edideolch_rec_nr',
 'v2edplural',
 'v2edplural_codelow',
 'v2edplural_codehigh',
 'v2edplural_sd',
 'v2edplural_osp',
 'v2edplural_osp_codelow',
 'v2edplural_osp_codehigh',
 'v2edplural_osp_sd',
 'v2edplural_ord',
 'v2edplural_ord_codelow',
 'v2edplural_ord_codehigh',
 'v2edplural_mean',
 'v2edplural_nr',
 'v2edcritical',
 'v2edcritical_codelow',
 'v2edcritical_codehigh',
 'v2edcritical_sd',
 'v2edcritical_osp',
 'v2edcritical_osp_codelow',
 'v2edcritical_osp_codehigh',
 'v2edcritical_osp_sd',
 'v2edcritical_ord',
 'v2edcritical_ord_codelow',
 'v2edcritical_ord_codehigh',
 'v2edcritical_mean',
 'v2edcritical_nr',
 'v2edteautonomy',
 'v2edteautonomy_codelow',
 'v2edteautonomy_codehigh',
 'v2edteautonomy_sd',
 'v2edteautonomy_osp',
 'v2edteautonomy_osp_codelow',
 'v2edteautonomy_osp_codehigh',
 'v2edteautonomy_osp_sd',
 'v2edteautonomy_ord',
 'v2edteautonomy_ord_codelow',
 'v2edteautonomy_ord_codehigh',
 'v2edteautonomy_mean',
 'v2edteautonomy_nr',
 'v2edmath',
 'v2edmath_codelow',
 'v2edmath_codehigh',
 'v2edmath_sd',
 'v2edmath_osp',
 'v2edmath_osp_codelow',
 'v2edmath_osp_codehigh',
 'v2edmath_osp_sd',
 'v2edmath_ord',
 'v2edmath_ord_codelow',
 'v2edmath_ord_codehigh',
 'v2edmath_mean',
 'v2edmath_mode',
 'v2edmath_nr',
 'v2edideolch_1',
 'v2edideolch_2',
 'v2edideolch_3',
 'v2edideolch_4',
 'v2edideolch_5',
 'v2edideolch_6',
 'v2edideolch_7',
 'v2edideolch_8',
 'v2edideolch_9',
 'v2edideolch_10',
 'v2edideolch_nr',
 'v2medstateprint',
 'v2medstateprint_codelow',
 'v2medstateprint_codehigh',
 'v2medstateprint_sd',
 'v2medstateprint_osp',
 'v2medstateprint_osp_codelow',
 'v2medstateprint_osp_codehigh',
 'v2medstateprint_osp_sd',
 'v2medstateprint_ord',
 'v2medstateprint_ord_codelow',
 'v2medstateprint_ord_codehigh',
 'v2medstateprint_mean',
 'v2medstateprint_nr',
 'v2medstatebroad',
 'v2medstatebroad_codelow',
 'v2medstatebroad_codehigh',
 'v2medstatebroad_sd',
 'v2medstatebroad_osp',
 'v2medstatebroad_osp_codelow',
 'v2medstatebroad_osp_codehigh',
 'v2medstatebroad_osp_sd',
 'v2medstatebroad_ord',
 'v2medstatebroad_ord_codelow',
 'v2medstatebroad_ord_codehigh',
 'v2medstatebroad_mean',
 'v2medstatebroad_nr',
 'v2medpolstate',
 'v2medpolstate_codelow',
 'v2medpolstate_codehigh',
 'v2medpolstate_sd',
 'v2medpolstate_osp',
 'v2medpolstate_osp_codelow',
 'v2medpolstate_osp_codehigh',
 'v2medpolstate_osp_sd',
 'v2medpolstate_ord',
 'v2medpolstate_ord_codelow',
 'v2medpolstate_ord_codehigh',
 'v2medpolstate_mean',
 'v2medpolstate_nr',
 'v2medpolnonstate',
 'v2medpolnonstate_codelow',
 'v2medpolnonstate_codehigh',
 'v2medpolnonstate_sd',
 'v2medpolnonstate_osp',
 'v2medpolnonstate_osp_codelow',
 'v2medpolnonstate_osp_codehigh',
 'v2medpolnonstate_osp_sd',
 'v2medpolnonstate_ord',
 'v2medpolnonstate_ord_codelow',
 'v2medpolnonstate_ord_codehigh',
 'v2medpolnonstate_mean',
 'v2medpolnonstate_nr',
 'v2medpatriot',
 'v2medpatriot_codelow',
 'v2medpatriot_codehigh',
 'v2medpatriot_sd',
 'v2medpatriot_osp',
 'v2medpatriot_osp_codelow',
 'v2medpatriot_osp_codehigh',
 'v2medpatriot_osp_sd',
 'v2medpatriot_ord',
 'v2medpatriot_ord_codelow',
 'v2medpatriot_ord_codehigh',
 'v2medpatriot_mean',
 'v2medpatriot_nr',
 'v2medentrain',
 'v2medentrain_codelow',
 'v2medentrain_codehigh',
 'v2medentrain_sd',
 'v2medentrain_osp',
 'v2medentrain_osp_codelow',
 'v2medentrain_osp_codehigh',
 'v2medentrain_osp_sd',
 'v2medentrain_ord',
 'v2medentrain_ord_codelow',
 'v2medentrain_ord_codehigh',
 'v2medentrain_mean',
 'v2medentrain_nr',
 'v2edscpatriot',
 'v2edscpatriot_codelow',
 'v2edscpatriot_codehigh',
 'v2edscpatriot_sd',
 'v2edscpatriot_osp',
 'v2edscpatriot_osp_codelow',
 'v2edscpatriot_osp_codehigh',
 'v2edscpatriot_osp_sd',
 'v2edscpatriot_ord',
 'v2edscpatriot_ord_codelow',
 'v2edscpatriot_ord_codehigh',
 'v2edscpatriot_mean',
 'v2edscpatriot_mode',
 'v2edscpatriot_nr',
 'v2edscpatriotcb',
 'v2edscpatriotcb_codelow',
 'v2edscpatriotcb_codehigh',
 'v2edscpatriotcb_sd',
 'v2edscpatriotcb_osp',
 'v2edscpatriotcb_osp_codelow',
 'v2edscpatriotcb_osp_codehigh',
 'v2edscpatriotcb_osp_sd',
 'v2edscpatriotcb_ord',
 'v2edscpatriotcb_ord_codelow',
 'v2edscpatriotcb_ord_codehigh',
 'v2edscpatriotcb_mean',
 'v2edscpatriotcb_nr',
 'v2edscextracurr',
 'v2edscextracurr_codelow',
 'v2edscextracurr_codehigh',
 'v2edscextracurr_sd',
 'v2edscextracurr_osp',
 'v2edscextracurr_osp_codelow',
 'v2edscextracurr_osp_codehigh',
 'v2edscextracurr_osp_sd',
 'v2edscextracurr_ord',
 'v2edscextracurr_ord_codelow',
 'v2edscextracurr_ord_codehigh',
 'v2edscextracurr_mean',
 'v2edscextracurr_nr',
 'v2edtequal',
 'v2edtequal_codelow',
 'v2edtequal_codehigh',
 'v2edtequal_sd',
 'v2edtequal_osp',
 'v2edtequal_osp_codelow',
 'v2edtequal_osp_codehigh',
 'v2edtequal_osp_sd',
 'v2edtequal_ord',
 'v2edtequal_ord_codelow',
 'v2edtequal_ord_codehigh',
 'v2edtequal_mean',
 'v2edtequal_nr',
 'v2temonitor',
 'v2temonitor_codelow',
 'v2temonitor_codehigh',
 'v2temonitor_sd',
 'v2temonitor_osp',
 'v2temonitor_osp_codelow',
 'v2temonitor_osp_codehigh',
 'v2temonitor_osp_sd',
 'v2temonitor_ord',
 'v2temonitor_ord_codelow',
 'v2temonitor_ord_codehigh',
 'v2temonitor_mean',
 'v2temonitor_nr',
 'v2edteunion',
 'v2edteunion_codelow',
 'v2edteunion_codehigh',
 'v2edteunion_sd',
 'v2edteunion_osp',
 'v2edteunion_osp_codelow',
 'v2edteunion_osp_codehigh',
 'v2edteunion_osp_sd',
 'v2edteunion_ord',
 'v2edteunion_ord_codelow',
 'v2edteunion_ord_codehigh',
 'v2edteunion_mean',
 'v2edteunion_mode',
 'v2edteunion_nr',
 'v2edteunionindp',
 'v2edteunionindp_codelow',
 'v2edteunionindp_codehigh',
 'v2edteunionindp_sd',
 'v2edteunionindp_osp',
 'v2edteunionindp_osp_codelow',
 'v2edteunionindp_osp_codehigh',
 'v2edteunionindp_osp_sd',
 'v2edteunionindp_ord',
 'v2edteunionindp_ord_codelow',
 'v2edteunionindp_ord_codehigh',
 'v2edteunionindp_mean',
 'v2edteunionindp_nr',
 'v2edtehire',
 'v2edtehire_codelow',
 'v2edtehire_codehigh',
 'v2edtehire_sd',
 'v2edtehire_osp',
 'v2edtehire_osp_codelow',
 'v2edtehire_osp_codehigh',
 'v2edtehire_osp_sd',
 'v2edtehire_ord',
 'v2edtehire_ord_codelow',
 'v2edtehire_ord_codehigh',
 'v2edtehire_mean',
 'v2edtehire_nr',
 'v2edtefire',
 'v2edtefire_codelow',
 'v2edtefire_codehigh',
 'v2edtefire_sd',
 'v2edtefire_osp',
 'v2edtefire_osp_codelow',
 'v2edtefire_osp_codehigh',
 'v2edtefire_osp_sd',
 'v2edtefire_ord',
 'v2edtefire_ord_codelow',
 'v2edtefire_ord_codehigh',
 'v2edtefire_mean',
 'v2edtefire_nr',
 'e_v2x_api_3C',
 'e_v2x_api_4C',
 'e_v2x_api_5C',
 'e_v2x_civlib_3C',
 'e_v2x_civlib_4C',
 'e_v2x_civlib_5C',
 'e_v2x_clphy_3C',
 'e_v2x_clphy_4C',
 'e_v2x_clphy_5C',
 'e_v2x_clpol_3C',
 'e_v2x_clpol_4C',
 'e_v2x_clpol_5C',
 'e_v2x_clpriv_3C',
 'e_v2x_clpriv_4C',
 'e_v2x_clpriv_5C',
 'e_v2x_corr_3C',
 'e_v2x_corr_4C',
 'e_v2x_corr_5C',
 'e_v2x_cspart_3C',
 'e_v2x_cspart_4C',
 'e_v2x_cspart_5C',
 'e_v2x_delibdem_3C',
 'e_v2x_delibdem_4C',
 'e_v2x_delibdem_5C',
 'e_v2x_EDcomp_thick_3C',
 'e_v2x_EDcomp_thick_4C',
 'e_v2x_EDcomp_thick_5C',

In [57]:
v_indicators

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,e_pefeliex,e_peinfmor,e_pelifeex,e_pematmor,e_wb_pop,e_civil_war,e_miinteco,e_miinterc,e_pt_coup,e_pt_coup_attempts
0,Mexico,MX,3,2010,12/31/2010,0,1,United Mexican States,1789,2022,...,NaN,17.40,75.3,47.0,114092961.0,NaN,NaN,NaN,0.0,0.0
1,Mexico,MX,3,2011,12/31/2011,0,1,United Mexican States,1789,2022,...,NaN,16.90,75.5,NaN,115695468.0,NaN,NaN,NaN,0.0,0.0
2,Mexico,MX,3,2012,12/31/2012,0,1,United Mexican States,1789,2022,...,NaN,16.40,75.7,NaN,117274156.0,NaN,NaN,NaN,0.0,0.0
3,Mexico,MX,3,2013,12/31/2013,0,1,United Mexican States,1789,2022,...,NaN,15.90,75.5,49.0,118827158.0,NaN,NaN,NaN,0.0,0.0
4,Mexico,MX,3,2014,12/31/2014,0,1,United Mexican States,1789,2022,...,NaN,15.40,75.6,NaN,120355137.0,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,Hungary,HU,210,2016,12/31/2016,0,1,Hungary,1789,2022,...,NaN,4.83,76.3,NaN,9814023.0,NaN,NaN,NaN,0.0,0.0
1942,Hungary,HU,210,2017,12/31/2017,0,1,Hungary,1789,2022,...,NaN,4.54,76.3,NaN,9787966.0,NaN,NaN,NaN,0.0,0.0
1943,Hungary,HU,210,2018,12/31/2018,0,1,Hungary,1789,2022,...,NaN,4.27,76.3,NaN,9775564.0,NaN,NaN,NaN,0.0,0.0
1944,Hungary,HU,210,2019,12/31/2019,0,1,Hungary,1789,2022,...,NaN,4.12,76.6,NaN,9771141.0,NaN,NaN,NaN,0.0,0.0
1945,Hungary,HU,210,2020,12/31/2020,0,1,Hungary,1789,2022,...,NaN,3.99,75.8,NaN,9750149.0,NaN,NaN,NaN,0.0,0.0

In [58]:

for col in indicator_columns:
    if (not(col in demo_columns)):
        v_indicators = v_indicators.drop(col, axis = 1)

v_indicators

,country_name,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2smgovfilcap,v2smgovfilcap_ord,v2smgovfilprc,v2smgovfilprc_ord,v2smgovshutcap,...,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
0,Mexico,2010,0.649,0.459,0.405,0.180,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.440,0.099,-0.726,0.0,8.0,8.0,178865.495,12105.354
1,Mexico,2011,0.647,0.457,0.405,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.475,0.257,-0.668,0.0,8.0,8.0,185824.148,12285.643
2,Mexico,2012,0.645,0.449,0.405,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.485,0.301,-0.662,0.0,8.0,8.0,192272.433,12475.351
3,Mexico,2013,0.618,0.416,0.364,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.592,0.307,-0.714,0.0,8.0,8.0,196479.952,12621.672
4,Mexico,2014,0.618,0.417,0.364,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.843,0.138,-0.854,0.0,8.0,8.0,201281.185,12794.271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,Hungary,2016,0.606,0.473,0.420,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.100,0.499,0.655,0.0,10.0,10.0,24215.278,1052.843
1942,Hungary,2017,0.561,0.443,0.388,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.119,0.523,0.807,0.0,10.0,10.0,25291.881,1050.901
1943,Hungary,2018,0.483,0.381,0.334,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.081,0.487,0.747,0.0,10.0,10.0,26452.517,1049.732
1944,Hungary,2019,0.466,0.368,0.323,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.056,0.492,0.772,NaN,NaN,NaN,27261.533,1055.913
1945,Hungary,2020,0.460,0.356,0.316,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.093,0.574,0.843,NaN,NaN,NaN,NaN,NaN

In [59]:
v_indicators["country_name"] = isos

In [60]:
v_indicators

,country_name,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2smgovfilcap,v2smgovfilcap_ord,v2smgovfilprc,v2smgovfilprc_ord,v2smgovshutcap,...,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop
0,MX,2010,0.649,0.459,0.405,0.180,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.440,0.099,-0.726,0.0,8.0,8.0,178865.495,12105.354
1,MX,2011,0.647,0.457,0.405,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.475,0.257,-0.668,0.0,8.0,8.0,185824.148,12285.643
2,MX,2012,0.645,0.449,0.405,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.485,0.301,-0.662,0.0,8.0,8.0,192272.433,12475.351
3,MX,2013,0.618,0.416,0.364,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.592,0.307,-0.714,0.0,8.0,8.0,196479.952,12621.672
4,MX,2014,0.618,0.417,0.364,0.108,2.0,1.783,4.0,-1.202,...,3.0,6.0,-0.843,0.138,-0.854,0.0,8.0,8.0,201281.185,12794.271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,HU,2016,0.606,0.473,0.420,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.100,0.499,0.655,0.0,10.0,10.0,24215.278,1052.843
1942,HU,2017,0.561,0.443,0.388,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.119,0.523,0.807,0.0,10.0,10.0,25291.881,1050.901
1943,HU,2018,0.483,0.381,0.334,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.081,0.487,0.747,0.0,10.0,10.0,26452.517,1049.732
1944,HU,2019,0.466,0.368,0.323,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.056,0.492,0.772,NaN,NaN,NaN,27261.533,1055.913
1945,HU,2020,0.460,0.356,0.316,0.452,2.0,1.145,4.0,-0.019,...,3.0,10.0,0.093,0.574,0.843,NaN,NaN,NaN,NaN,NaN

In [61]:
instances = CountryCodes(instances, "country_id", name_to_alpha_2)

In [62]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010,AQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1558,2020,WS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1559,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1560,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1561,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
def ExcludeStates(x, country_col, states, keep):
    if (keep == True):
        if (x[country_col] in states):
            return True
        return False
    else:
        if (x[country_col] in states):
            return False
        return True

def RemoveStates(data, country_col, states, keep = False):
    keep = data.apply(lambda x: ExcludeStates(x, country_col, states, keep), axis = 1)
    data = data[keep]
    data = data.reset_index(drop = True)
    return data

In [64]:
instances = RemoveStates(instances, "country_id", list(v_indicators["country_name"]), keep = True)

In [65]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Satellite calibration centre,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
instances["Year-Country"] = instances["year_commenced"].astype(str) + "," + instances["country_id"]

In [67]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,Smart cities,Subsidiary,Surveillance equipment,Telecommunications or ICT,Training,Artificial Intelligence,Biotech,Chinese state loan,Surveillance,Year-Country
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2010,AE"
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2010,AF"
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2010,AM"
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2010,AO"
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2010,AR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2020,VN"
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2020,VU"
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2020,ZA"
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2020,ZM"
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2020,ZW"

In [68]:
v_indicators["Year-Country"] = v_indicators["year"].astype(str) +"," + v_indicators["country_name"]

In [69]:
v_indicators

,country_name,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2smgovfilcap,v2smgovfilcap_ord,v2smgovfilprc,v2smgovfilprc_ord,v2smgovshutcap,...,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,e_pop,Year-Country
0,MX,2010,0.649,0.459,0.405,0.180,2.0,1.783,4.0,-1.202,...,6.0,-0.440,0.099,-0.726,0.0,8.0,8.0,178865.495,12105.354,"2010,MX"
1,MX,2011,0.647,0.457,0.405,0.108,2.0,1.783,4.0,-1.202,...,6.0,-0.475,0.257,-0.668,0.0,8.0,8.0,185824.148,12285.643,"2011,MX"
2,MX,2012,0.645,0.449,0.405,0.108,2.0,1.783,4.0,-1.202,...,6.0,-0.485,0.301,-0.662,0.0,8.0,8.0,192272.433,12475.351,"2012,MX"
3,MX,2013,0.618,0.416,0.364,0.108,2.0,1.783,4.0,-1.202,...,6.0,-0.592,0.307,-0.714,0.0,8.0,8.0,196479.952,12621.672,"2013,MX"
4,MX,2014,0.618,0.417,0.364,0.108,2.0,1.783,4.0,-1.202,...,6.0,-0.843,0.138,-0.854,0.0,8.0,8.0,201281.185,12794.271,"2014,MX"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,HU,2016,0.606,0.473,0.420,0.452,2.0,1.145,4.0,-0.019,...,10.0,0.100,0.499,0.655,0.0,10.0,10.0,24215.278,1052.843,"2016,HU"
1942,HU,2017,0.561,0.443,0.388,0.452,2.0,1.145,4.0,-0.019,...,10.0,0.119,0.523,0.807,0.0,10.0,10.0,25291.881,1050.901,"2017,HU"
1943,HU,2018,0.483,0.381,0.334,0.452,2.0,1.145,4.0,-0.019,...,10.0,0.081,0.487,0.747,0.0,10.0,10.0,26452.517,1049.732,"2018,HU"
1944,HU,2019,0.466,0.368,0.323,0.452,2.0,1.145,4.0,-0.019,...,10.0,0.056,0.492,0.772,NaN,NaN,NaN,27261.533,1055.913,"2019,HU"
1945,HU,2020,0.460,0.356,0.316,0.452,2.0,1.145,4.0,-0.019,...,10.0,0.093,0.574,0.843,NaN,NaN,NaN,NaN,NaN,"2020,HU"

In [70]:
def ApplyIndex(x, index_data, col_range, year_country_col):
    year_country = x[year_country_col]
    filtered = index_data.loc[index_data[year_country_col] == year_country, 
                              index_data.columns[col_range[0]:col_range[1]]]
    filtered = pd.Series(filtered.iloc[0])
    return filtered

In [71]:
def AddIndexCols(data, index_data, col_range, year_country_col):
    newcols = data.apply(lambda x: ApplyIndex(x, index_data, col_range, year_country_col), axis = 1, 
                         result_type = "expand")
    data = pd.concat([data, newcols], axis = 1)
    return data

In [72]:
instances = AddIndexCols(instances, v_indicators, [2,29], "Year-Country")

In [73]:
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,4.0,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,2.0,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,6.0,6.0,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,4.0,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,10.0,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,7.0,4.0,-0.352,0.230,-0.080,NaN,NaN,NaN,NaN
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,13.0,-0.146,-0.398,0.913,NaN,NaN,NaN,NaN
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,9.0,-0.011,0.097,-0.241,NaN,NaN,NaN,NaN
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,8.0,-0.724,-0.802,-0.130,NaN,NaN,NaN,NaN
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,2.0,-1.289,-1.300,-1.072,NaN,NaN,NaN,NaN

In [74]:
instances  = instances.drop(columns = ["Year-Country"])
instances

,year_commenced,country_id,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_fh_cl,e_fh_pr,e_fh_rol,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,4.0,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,2.0,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,6.0,6.0,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,4.0,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,10.0,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,7.0,4.0,-0.352,0.230,-0.080,NaN,NaN,NaN,NaN
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,13.0,-0.146,-0.398,0.913,NaN,NaN,NaN,NaN
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,9.0,-0.011,0.097,-0.241,NaN,NaN,NaN,NaN
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,8.0,-0.724,-0.802,-0.130,NaN,NaN,NaN,NaN
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,6.0,2.0,-1.289,-1.300,-1.072,NaN,NaN,NaN,NaN

In [75]:
force = pd.read_csv("../Surveillance Output/summarized_force.csv")
peaceful = pd.read_csv("../Surveillance Output/summarized_peaceful.csv")
intervention = pd.read_csv("../Surveillance Output/summarized_intervention.csv")

In [76]:
instances.to_csv('test1.csv')

In [77]:
force = CountryCodes(force, "country", name_to_alpha_2)
peaceful = CountryCodes(peaceful, "country", name_to_alpha_2)
intervention = CountryCodes(intervention, "country", name_to_alpha_2)

In [78]:
force

     year country  force_count
0    2010      BD         11.0
1    2010      BJ          1.0
2    2010      KH          2.0
3    2010      CF          2.0
4    2010      CD          1.0
..    ...     ...          ...
442  2020      UG          4.0
443  2020      US        116.0
444  2020      VE         14.0
445  2020      YE         13.0
446  2020      ZM          2.0

[447 rows x 3 columns]

In [79]:
instances = instances.set_index(["year_commenced", "country_id"])

In [80]:
instances

                            5G  Cable Terrestrial  Commercial partnership  \
year_commenced country_id
2010           AE          0.0                0.0                     0.0
               AF          0.0                0.0                     0.0
               AM          0.0                0.0                     0.0
               AO          0.0                0.0                     0.0
               AR          0.0                0.0                     0.0
...                        ...                ...                     ...
2020           VN          0.0                0.0                     0.0
               VU          0.0                0.0                     0.0
               ZA          0.0                0.0                     0.0
               ZM          0.0                0.0                     0.0
               ZW          0.0                0.0                     0.0

                           Data centre  Facial recognition  \
year_commenced country_id
2010           AE                  0.0                 0.0
               AF                  0.0                 0.0
               AM                  0.0                 0.0
               AO                  0.0                 0.0
               AR                  0.0                 0.0
...                                ...                 ...
2020           VN                  0.0                 0.0
               VU                  0.0                 0.0
               ZA                  0.0                 0.0
               ZM                  0.0                 0.0
               ZW                  0.0                 0.0

                           Investment or joint venture  Investor  \
year_commenced country_id
2010           AE                                  0.0       0.0
               AF                                  0.0       0.0
               AM                                  0.0       0.0
               AO                                  0.0       0.0
               AR                                  0.0       0.0
...                                                ...       ...
2020           VN                                  0.0       0.0
               VU                                  0.0       0.0
               ZA                                  0.0       0.0
               ZM                                  0.0       0.0
               ZW                                  0.0       0.0

                           Manufacturing facility  MoU-agreement  \
year_commenced country_id
2010           AE                             0.0            0.0
               AF                             0.0            0.0
               AM                             0.0            0.0
               AO                             0.0            0.0
               AR                             0.0            0.0
...                                           ...            ...
2020           VN                             0.0            0.0
               VU                             0.0            0.0
               ZA                             0.0            0.0
               ZM                             0.0            0.0
               ZW                             0.0            0.0

                           Overseas Office  ...  e_fh_cl  e_fh_pr  e_fh_rol  \
year_commenced country_id                   ...
2010           AE                      0.0  ...      5.0      6.0       4.0
               AF                      0.0  ...      6.0      6.0       2.0
               AM                      0.0  ...      4.0      6.0       6.0
               AO                      0.0  ...      5.0      6.0       4.0
               AR                      0.0  ...      2.0      2.0      10.0
...                                    ...  ...      ...      ...       ...
2020           VN                      0.0  ...      6.0      7.0       4.0
               VU                      0.0  ...      2.0      2.0      13.0
               ZA                      0.0  ...      2.0      2.0       9.0
               ZM                      0.0  ...      4.0      4.0       8.0
               ZW                      0.0  ...      5.0      6.0       2.0

                           e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  \
year_commenced country_id
2010           AE               0.891       0.893       0.802      8.0
               AF              -1.645      -1.481      -2.579    -66.0
               AM              -0.695      -0.166       0.072      0.0
               AO              -1.332      -1.142      -0.226      4.0
               AR              -0.355      -0.111      -0.085      0.0
...                               ...         ...         ...      ...
2020           VN              -0.352       0.230      -0.080      NaN
               VU              -0.146      -0.398       0.913      NaN
               ZA              -0.011       0.097      -0.241      NaN
               ZM              -0.724      -0.802      -0.130      NaN
               ZW              -1.289      -1.300      -1.072      NaN

                           e_democ  e_p_polity      e_gdp
year_commenced country_id
2010           AE              0.0        -8.0  52870.586
               AF            -66.0       -66.0   4817.654
               AM              5.0         5.0   2585.193
               AO              2.0        -2.0  12808.053
               AR              8.0         8.0  71367.171
...                            ...         ...        ...
2020           VN              NaN         NaN        NaN
               VU              NaN         NaN        NaN
               ZA              NaN         NaN        NaN
               ZM              NaN         NaN        NaN
               ZW              NaN         NaN        NaN

[1485 rows x 49 columns]

In [81]:
force = force.set_index(["year", "country"])

In [82]:
instances = pd.concat([instances, force], axis = 1)

In [83]:
instances

          5G  Cable Terrestrial  Commercial partnership  Data centre  \
2010 AE  0.0                0.0                     0.0          0.0
     AF  0.0                0.0                     0.0          0.0
     AM  0.0                0.0                     0.0          0.0
     AO  0.0                0.0                     0.0          0.0
     AR  0.0                0.0                     0.0          0.0
...      ...                ...                     ...          ...
2020 MZ  NaN                NaN                     NaN          NaN
     PN  NaN                NaN                     NaN          NaN
     SO  NaN                NaN                     NaN          NaN
     SY  NaN                NaN                     NaN          NaN
     YE  NaN                NaN                     NaN          NaN

         Facial recognition  Investment or joint venture  Investor  \
2010 AE                 0.0                          0.0       0.0
     AF                 0.0                          0.0       0.0
     AM                 0.0                          0.0       0.0
     AO                 0.0                          0.0       0.0
     AR                 0.0                          0.0       0.0
...                     ...                          ...       ...
2020 MZ                 NaN                          NaN       NaN
     PN                 NaN                          NaN       NaN
     SO                 NaN                          NaN       NaN
     SY                 NaN                          NaN       NaN
     YE                 NaN                          NaN       NaN

         Manufacturing facility  MoU-agreement  Overseas Office  ...  e_fh_pr  \
2010 AE                     0.0            0.0              0.0  ...      6.0
     AF                     0.0            0.0              0.0  ...      6.0
     AM                     0.0            0.0              0.0  ...      6.0
     AO                     0.0            0.0              0.0  ...      6.0
     AR                     0.0            0.0              0.0  ...      2.0
...                         ...            ...              ...  ...      ...
2020 MZ                     NaN            NaN              NaN  ...      NaN
     PN                     NaN            NaN              NaN  ...      NaN
     SO                     NaN            NaN              NaN  ...      NaN
     SY                     NaN            NaN              NaN  ...      NaN
     YE                     NaN            NaN              NaN  ...      NaN

         e_fh_rol  e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  \
2010 AE       4.0       0.891       0.893       0.802      8.0      0.0
     AF       2.0      -1.645      -1.481      -2.579    -66.0    -66.0
     AM       6.0      -0.695      -0.166       0.072      0.0      5.0
     AO       4.0      -1.332      -1.142      -0.226      4.0      2.0
     AR      10.0      -0.355      -0.111      -0.085      0.0      8.0
...           ...         ...         ...         ...      ...      ...
2020 MZ       NaN         NaN         NaN         NaN      NaN      NaN
     PN       NaN         NaN         NaN         NaN      NaN      NaN
     SO       NaN         NaN         NaN         NaN      NaN      NaN
     SY       NaN         NaN         NaN         NaN      NaN      NaN
     YE       NaN         NaN         NaN         NaN      NaN      NaN

         e_p_polity      e_gdp  force_count
2010 AE        -8.0  52870.586          NaN
     AF       -66.0   4817.654          NaN
     AM         5.0   2585.193          NaN
     AO        -2.0  12808.053          NaN
     AR         8.0  71367.171          NaN
...             ...        ...          ...
2020 MZ         NaN        NaN          1.0
     PN         NaN        NaN         15.0
     SO         NaN        NaN         11.0
     SY         NaN        NaN         15.0
     YE         NaN        NaN         13.0

[1571 rows x 50 columns]

In [84]:
peaceful = peaceful.set_index(["year", "country"])

In [85]:
instances = pd.concat([instances, peaceful], axis = 1)

In [86]:
intervention = intervention.set_index(["year", "country"])

In [87]:
instances = pd.concat([instances, intervention], axis = 1)

In [88]:
instances

          5G  Cable Terrestrial  Commercial partnership  Data centre  \
2010 AE  0.0                0.0                     0.0          0.0
     AF  0.0                0.0                     0.0          0.0
     AM  0.0                0.0                     0.0          0.0
     AO  0.0                0.0                     0.0          0.0
     AR  0.0                0.0                     0.0          0.0
...      ...                ...                     ...          ...
2013 GQ  NaN                NaN                     NaN          NaN
     CG  NaN                NaN                     NaN          NaN
2015 GW  NaN                NaN                     NaN          NaN
2019 BQ  NaN                NaN                     NaN          NaN
2020 GQ  NaN                NaN                     NaN          NaN

         Facial recognition  Investment or joint venture  Investor  \
2010 AE                 0.0                          0.0       0.0
     AF                 0.0                          0.0       0.0
     AM                 0.0                          0.0       0.0
     AO                 0.0                          0.0       0.0
     AR                 0.0                          0.0       0.0
...                     ...                          ...       ...
2013 GQ                 NaN                          NaN       NaN
     CG                 NaN                          NaN       NaN
2015 GW                 NaN                          NaN       NaN
2019 BQ                 NaN                          NaN       NaN
2020 GQ                 NaN                          NaN       NaN

         Manufacturing facility  MoU-agreement  Overseas Office  ...  \
2010 AE                     0.0            0.0              0.0  ...
     AF                     0.0            0.0              0.0  ...
     AM                     0.0            0.0              0.0  ...
     AO                     0.0            0.0              0.0  ...
     AR                     0.0            0.0              0.0  ...
...                         ...            ...              ...  ...
2013 GQ                     NaN            NaN              NaN  ...
     CG                     NaN            NaN              NaN  ...
2015 GW                     NaN            NaN              NaN  ...
2019 BQ                     NaN            NaN              NaN  ...
2020 GQ                     NaN            NaN              NaN  ...

         e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  e_p_polity  \
2010 AE       0.891       0.893       0.802      8.0      0.0        -8.0
     AF      -1.645      -1.481      -2.579    -66.0    -66.0       -66.0
     AM      -0.695      -0.166       0.072      0.0      5.0         5.0
     AO      -1.332      -1.142      -0.226      4.0      2.0        -2.0
     AR      -0.355      -0.111      -0.085      0.0      8.0         8.0
...             ...         ...         ...      ...      ...         ...
2013 GQ         NaN         NaN         NaN      NaN      NaN         NaN
     CG         NaN         NaN         NaN      NaN      NaN         NaN
2015 GW         NaN         NaN         NaN      NaN      NaN         NaN
2019 BQ         NaN         NaN         NaN      NaN      NaN         NaN
2020 GQ         NaN         NaN         NaN      NaN      NaN         NaN

             e_gdp  force_count  peaceful_count  intervention_count
2010 AE  52870.586          NaN             NaN                 NaN
     AF   4817.654          NaN             NaN                 NaN
     AM   2585.193          NaN             NaN                 NaN
     AO  12808.053          NaN             NaN                 NaN
     AR  71367.171          NaN             NaN                 NaN
...            ...          ...             ...                 ...
2013 GQ        NaN          NaN             NaN                 1.0
     CG        NaN          NaN             NaN                 1.0
2015 GW        NaN          NaN             NaN                 1.0
2019 BQ        NaN          NaN             NaN                 1.0
2020 GQ        NaN          NaN             NaN                 1.0

[1763 rows x 52 columns]

In [89]:
instances = instances.dropna(subset = "5G")

In [90]:
instances

          5G  Cable Terrestrial  Commercial partnership  Data centre  \
2010 AE  0.0                0.0                     0.0          0.0
     AF  0.0                0.0                     0.0          0.0
     AM  0.0                0.0                     0.0          0.0
     AO  0.0                0.0                     0.0          0.0
     AR  0.0                0.0                     0.0          0.0
...      ...                ...                     ...          ...
2020 VN  0.0                0.0                     0.0          0.0
     VU  0.0                0.0                     0.0          0.0
     ZA  0.0                0.0                     0.0          0.0
     ZM  0.0                0.0                     0.0          0.0
     ZW  0.0                0.0                     0.0          0.0

         Facial recognition  Investment or joint venture  Investor  \
2010 AE                 0.0                          0.0       0.0
     AF                 0.0                          0.0       0.0
     AM                 0.0                          0.0       0.0
     AO                 0.0                          0.0       0.0
     AR                 0.0                          0.0       0.0
...                     ...                          ...       ...
2020 VN                 0.0                          0.0       0.0
     VU                 0.0                          0.0       0.0
     ZA                 0.0                          0.0       0.0
     ZM                 0.0                          0.0       0.0
     ZW                 0.0                          0.0       0.0

         Manufacturing facility  MoU-agreement  Overseas Office  ...  \
2010 AE                     0.0            0.0              0.0  ...
     AF                     0.0            0.0              0.0  ...
     AM                     0.0            0.0              0.0  ...
     AO                     0.0            0.0              0.0  ...
     AR                     0.0            0.0              0.0  ...
...                         ...            ...              ...  ...
2020 VN                     0.0            0.0              0.0  ...
     VU                     0.0            0.0              0.0  ...
     ZA                     0.0            0.0              0.0  ...
     ZM                     0.0            0.0              0.0  ...
     ZW                     0.0            0.0              0.0  ...

         e_wbgi_cce  e_wbgi_gee  e_wbgi_pve  e_autoc  e_democ  e_p_polity  \
2010 AE       0.891       0.893       0.802      8.0      0.0        -8.0
     AF      -1.645      -1.481      -2.579    -66.0    -66.0       -66.0
     AM      -0.695      -0.166       0.072      0.0      5.0         5.0
     AO      -1.332      -1.142      -0.226      4.0      2.0        -2.0
     AR      -0.355      -0.111      -0.085      0.0      8.0         8.0
...             ...         ...         ...      ...      ...         ...
2020 VN      -0.352       0.230      -0.080      NaN      NaN         NaN
     VU      -0.146      -0.398       0.913      NaN      NaN         NaN
     ZA      -0.011       0.097      -0.241      NaN      NaN         NaN
     ZM      -0.724      -0.802      -0.130      NaN      NaN         NaN
     ZW      -1.289      -1.300      -1.072      NaN      NaN         NaN

             e_gdp  force_count  peaceful_count  intervention_count
2010 AE  52870.586          NaN             NaN                 NaN
     AF   4817.654          NaN             NaN                 NaN
     AM   2585.193          NaN             NaN                 NaN
     AO  12808.053          NaN             NaN                 NaN
     AR  71367.171          NaN             NaN                 NaN
...            ...          ...             ...                 ...
2020 VN        NaN          NaN             7.0                 2.0
     VU        NaN          NaN             NaN                 NaN
     ZA        NaN          2.0           998.0                67.0
     ZM        NaN          2.0             5.0                 1.0
     ZW        NaN          NaN            35.0                17.0

[1485 rows x 52 columns]

In [91]:
instances = instances.reset_index()

In [92]:
instances

,level_0,level_1,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,force_count,peaceful_count,intervention_count
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586,NaN,NaN,NaN
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654,NaN,NaN,NaN
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193,NaN,NaN,NaN
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053,NaN,NaN,NaN
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.352,0.230,-0.080,NaN,NaN,NaN,NaN,NaN,7.0,2.0
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.146,-0.398,0.913,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.011,0.097,-0.241,NaN,NaN,NaN,NaN,2.0,998.0,67.0
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.724,-0.802,-0.130,NaN,NaN,NaN,NaN,2.0,5.0,1.0
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.289,-1.300,-1.072,NaN,NaN,NaN,NaN,NaN,35.0,17.0

In [93]:
instances = instances.rename({"level_0": "year", "level_1": "country"}, axis =1)

In [94]:
instances

,year,country,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,force_count,peaceful_count,intervention_count
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586,NaN,NaN,NaN
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654,NaN,NaN,NaN
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193,NaN,NaN,NaN
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053,NaN,NaN,NaN
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,2020,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.352,0.230,-0.080,NaN,NaN,NaN,NaN,NaN,7.0,2.0
1481,2020,VU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.146,-0.398,0.913,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,2020,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.011,0.097,-0.241,NaN,NaN,NaN,NaN,2.0,998.0,67.0
1483,2020,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.724,-0.802,-0.130,NaN,NaN,NaN,NaN,2.0,5.0,1.0
1484,2020,ZW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.289,-1.300,-1.072,NaN,NaN,NaN,NaN,NaN,35.0,17.0

In [95]:
instances.to_csv("test2.csv")

In [96]:
instances = instances.dropna(subset = instances.columns[0:51])

In [97]:
instances

,year,country,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,force_count,peaceful_count,intervention_count
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586,NaN,NaN,NaN
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654,NaN,NaN,NaN
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193,NaN,NaN,NaN
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053,NaN,NaN,NaN
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,2018,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.489,0.003,0.059,7.0,0.0,-7.0,68613.592,1.0,34.0,3.0
1212,2018,ZA,4.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,-0.112,0.133,-0.228,0.0,9.0,9.0,69542.681,7.0,488.0,34.0
1213,2018,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.657,-0.625,0.086,0.0,6.0,6.0,5358.391,NaN,12.0,3.0
1214,2018,ZW,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,-1.228,-1.262,-0.723,1.0,5.0,4.0,4857.211,1.0,52.0,17.0
1341,2019,US,3.0,0.0,19.0,0.0,0.0,3.0,1.0,0.0,...,1.212,1.482,0.135,0.0,7.0,7.0,2118706.309,NaN,NaN,NaN

In [98]:
instances = instances.replace({np.nan: 0})

In [99]:
instances

,year,country,5G,Cable Terrestrial,Commercial partnership,Data centre,Facial recognition,Investment or joint venture,Investor,Manufacturing facility,...,e_wbgi_cce,e_wbgi_gee,e_wbgi_pve,e_autoc,e_democ,e_p_polity,e_gdp,force_count,peaceful_count,intervention_count
0,2010,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.891,0.893,0.802,8.0,0.0,-8.0,52870.586,0.0,0.0,0.0
1,2010,AF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.645,-1.481,-2.579,-66.0,-66.0,-66.0,4817.654,0.0,0.0,0.0
2,2010,AM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.695,-0.166,0.072,0.0,5.0,5.0,2585.193,0.0,0.0,0.0
3,2010,AO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.332,-1.142,-0.226,4.0,2.0,-2.0,12808.053,0.0,0.0,0.0
4,2010,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.355,-0.111,-0.085,0.0,8.0,8.0,71367.171,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,2018,VN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.489,0.003,0.059,7.0,0.0,-7.0,68613.592,1.0,34.0,3.0
1212,2018,ZA,4.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,-0.112,0.133,-0.228,0.0,9.0,9.0,69542.681,7.0,488.0,34.0
1213,2018,ZM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.657,-0.625,0.086,0.0,6.0,6.0,5358.391,0.0,12.0,3.0
1214,2018,ZW,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,-1.228,-1.262,-0.723,1.0,5.0,4.0,4857.211,1.0,52.0,17.0
1341,2019,US,3.0,0.0,19.0,0.0,0.0,3.0,1.0,0.0,...,1.212,1.482,0.135,0.0,7.0,7.0,2118706.309,0.0,0.0,0.0

In [ ]:
instances.to_csv('')